#!/bin/bash


i="0"
while [ $i -lt 20 ] #20 amostras
do

        t1=$(date +%s%3N) #display time in ubuntu (ms)
#	sudo boot build/firewall161 
	cd build && ./run
	echo "Reading: "
	read t2
        bt=$((t2 - t1))
	cd ..
        echo "Boot time" $[$i+1] "=" $bt "ms" >> boots_stf.txt
        i=$[$i+1]
done

